USE [master]
GO

CREATE DATABASE [Pagamento]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pagamento', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Pagamento.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Pagamento_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Pagamento_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Pagamento] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pagamento].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pagamento] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pagamento] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pagamento] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pagamento] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pagamento] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pagamento] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Pagamento] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pagamento] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pagamento] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pagamento] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pagamento] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pagamento] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pagamento] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pagamento] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pagamento] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Pagamento] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pagamento] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pagamento] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pagamento] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pagamento] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pagamento] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Pagamento] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pagamento] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Pagamento] SET  MULTI_USER 
GO

ALTER DATABASE [Pagamento] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pagamento] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pagamento] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Pagamento] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Pagamento] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Pagamento] SET QUERY_STORE = OFF
GO

USE [Pagamento]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Pagamento] SET  READ_WRITE 
GO

